---
title: "phenotyping"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{phenotyping}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(heRmes)
```

View the available phenotypes
```{r ids}
# top 5 phenotypes
get_phenotypes()[1:5]
```

View the codes for phenotype `PH_HF_HERMES_3.0`
```{r codes}
# top 5 codes
get_codes(pheno_id = "PH_HF_HERMES_3.0")[1:5, c("phenotype_id", "phenotype_name", "coding_system.name", "code")]
```

Create sample data in long format.
```{r create_data}
set.seed(2020)
n   <- 10
dat <- data.frame(ids   = paste0("ID_", c(1:(n/2), 1:(n/2))), 
                  codes = sample(c("I420", "foo", "bar", "baz"), n, replace = TRUE))
dat
```

Phenotype the individuals with phenotype `PH_HF_HERMES_3.0`, excluding phenotype `PH_congHD_HERMES_3.0`
```{r phenotype}
result <- phenotype(dat$ids, dat$codes, 
                    name    = "Heart Failure", 
                    include = "PH_HF_HERMES_3.0", 
                    exclude = "PH_congHD_HERMES_3.0")
result[]
```

